### ISSUE TITLE
Browsing Primary Action Flow

### ISSUE THREAD

**Issue by bsteinbeigle** [Methodician/guytime#127]

**Comment by bsteinbeigle** [comment]
@kaxline I know we briefly talked about going away from being able to message someone without their consent when clicking through profles so here on my thought on how it should work so we can test. 

1) Browse someone profiles whom are interested in connecting with. 
2) Send them a "message request" that basically says something like-Keith is in your area and wants to talk/hangout. Start the convo.-This could simply be just the first message in a messaging string that would automatically be created when you tap the message button when browsing profiles. If we can setup a text notification which means we would need someone's phone number that may be best. That way someone would know that Keith was trying to reach out to him. I't sounds like setting up push notifications on a web app is a bit of pain so maybe this is a good work around? 


Let me know if this makes sense...

**Comment by kaxline** [comment]
OK, from all the discussion about notifications, it seems clear that we should adopt Firebase Cloud Messaging:

https://firebase.google.com/docs/cloud-messaging/

Which will allow us to get as close to Push Notifications as we can across platforms.

While I get that ready, though, I think we need to map out these new flows to make sure we're on the same page. It sounds like this is getting pretty complicated (especially the concept of draft messsages) and will probably push back an MVP release if we need it to be included.

Something that I could implement sooner would be this:

- User messages another user (receiver) that they're not connected to yet – via the profile browser
- The receiving user sees a message in their message list that looks a little different than the rest, and it has an "accept" and "ignore" button.
- The sending user sees a chat show up in their chat list that has some sort of "pending" status.
- If the receiving user accepts, a Connection is made between the two users
- Both users can now see each other in their respective Connections list

We could get this out there and then worry about notifications and drafts later on. If those need to be a part of the MVP, we should probably plan on an end of August release.

As it is, it might be tight trying to make July as more of these details become clear. But we're still good on my hours so I can make a push on what we've outlined above and see how we do.

**Comment by bsteinbeigle** [comment]
@kaxline thanks for sending. The proposed flow above works for me. We can tweak down the road as we get it in front of users.

**Comment by kaxline** [comment]
@bsteinbeigle OK, I just deployed an update that has a draft of the flow outlined above, but here's a better description.

As a user browses profiles, they see a "wave" icon if they're not connected to that person (we can change this to whatever).

If they message a non-connection, then they see a message saying that they're not connected with that person and they're waiting for the other person to respond.

The person receiving the message then sees the message and instead of a chat box, they are prompted to either ignore the person or add them as a connection. 

In this flow, only people who are connected can chat 1-on-1, but I haven't implemented anything for group chats.

Currently there is no way to undo an "ignore" or remove a connection.

Let's close this issue and then open separate ones for more specific changes as needed.
